apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logmind.fullname" . }}-worker
  labels:
    {{- include "logmind.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      {{- include "logmind.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "logmind.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - logmind.core.celery_app
            - worker
            - --loglevel=info
            - --concurrency={{ .Values.config.celery.concurrency }}
            - -Q
            - analysis,alert,rag,celery
          envFrom:
            - configMapRef:
                name: {{ include "logmind.fullname" . }}-config
            - secretRef:
                name: {{ include "logmind.fullname" . }}-secret
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logmind.fullname" . }}-beat
  labels:
    {{- include "logmind.labels" . | nindent 4 }}
    app.kubernetes.io/component: beat
spec:
  replicas: {{ .Values.replicaCount.beat }}
  selector:
    matchLabels:
      {{- include "logmind.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: beat
  template:
    metadata:
      labels:
        {{- include "logmind.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: beat
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: beat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - logmind.core.celery_app
            - beat
            - --loglevel=info
          envFrom:
            - configMapRef:
                name: {{ include "logmind.fullname" . }}-config
            - secretRef:
                name: {{ include "logmind.fullname" . }}-secret
          resources:
            {{- toYaml .Values.beat.resources | nindent 12 }}
