apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logmind.fullname" . }}-secret
  labels:
    {{- include "logmind.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "logmind.databaseUrl" . | quote }}
  REDIS_URL: {{ include "logmind.redisUrl" . | quote }}
  CELERY_BROKER_URL: {{ include "logmind.celeryBrokerUrl" . | quote }}
  CELERY_RESULT_BACKEND: "redis://{{ .Values.config.redis.host }}:{{ .Values.config.redis.port }}/{{ .Values.config.celery.resultDb }}"
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  {{- if .Values.config.elasticsearch.password }}
  ES_PASSWORD: {{ .Values.config.elasticsearch.password | quote }}
  {{- end }}
